---
- name: Create AristaSwitch VLANs
  hosts: arista
  tasks:
    - name: Configure Vlans
      eos_vlan: name={{item.name}}
                vlanid={{item.vlanid}}
                username={{eapi_username}}
                password={{eapi_password}}
                host={{eapi_hostname}}
                port={{eapi_port}}
                transport=https
      with_items:
        - {name: MAGGIE, vlanid: 257}
        - {name: JOHNNY, vlanid: 258}
        - {name: REGGIE, vlanid: 259}
