---
- name: Configure AristaSwitch Interfaces
  hosts: arista
  tasks:
    - name: Configure Interfaces
      eos_interface: name=Ethernet5
                description="***IN USE***"
                username={{eapi_username}}
                password={{eapi_password}}
                host={{eapi_hostname}}
                port={{eapi_port}}
                transport=https
    - name: Configure Switchport
      eos_switchport: name=Ethernet5
                mode=access
                access_vlan=257
                username={{eapi_username}}
                password={{eapi_password}}
                host={{eapi_hostname}}
                port={{eapi_port}}
                transport=https
