---
- name: Configure AristaSwitch Interfaces
  hosts: arista
  tasks:
    - name: Configure Switchport as Trunk
      eos_switchport: name=Ethernet5
                mode=trunk
                trunk_native_vlan=1
                trunk_allowed_vlans=257,258,259
                username={{eapi_username}}
                password={{eapi_password}}
                host={{eapi_hostname}}
                port={{eapi_port}}
                transport=https
